version: "3.11"

services:
  auth: &auth_conf
    build: ./auth_service
    volumes:
      - ./auth_service/app:/app
    depends_on:
      - db
      - auth_migrate
    env_file:
      - ./auth_service/app/.env
    ports:
      - "80:8000"

  auth_migrate:
    <<: *auth_conf
    command: python3 manage.py migrate
    depends_on: 
      db:
        condition: service_healthy
    ports: []

  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 5
      start_period: 1s


volumes:
  db: {}
